# -*- coding: utf-8 -*-
"""final_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19f6UvSGhGb4qdlq3o89AxVBz3XFAF0S5
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import gradio as gr

def process_temperature_map(image, region_name):
    # Convert image to RGB
    img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Reshape pixels
    pixels = img.reshape(-1, 3).astype(np.float32)

    K = 9
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 50, 0.2)

    _, labels, centers = cv2.kmeans(
        pixels, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS
    )

    labels = labels.reshape(img.shape[:2])
    centers = centers.astype(int)

    # Sort clusters using HSV (cold → warm)
    centers_hsv = cv2.cvtColor(
        centers.reshape(-1, 1, 3).astype(np.uint8),
        cv2.COLOR_RGB2HSV
    ).reshape(-1, 3)

    sorted_idx = np.argsort(centers_hsv[:, 0])[::-1]

    new_labels = np.zeros_like(labels)
    new_centers = []

    for new_i, old_i in enumerate(sorted_idx):
        new_labels[labels == old_i] = new_i
        new_centers.append(centers[old_i])

    new_centers = np.array(new_centers)

    region_names = {
        0: "extreme cold",
        1: "very cold",
        2: "moderate cold",
        3: "near normal",
        4: "slight warm",
        5: "moderate warm",
        6: "strong warm",
        7: "very strong warm",
        8: "extreme warm"
    }

    name_to_class = {v: k for k, v in region_names.items()}

    class_id = name_to_class[region_name]

    # Highlight selected region
    mask = new_labels == class_id
    highlighted = img.copy()
    highlighted[~mask] = [180, 180, 180]  # gray background

    return highlighted


# ----------- GRADIO UI -----------
interface = gr.Interface(
    fn=process_temperature_map,
    inputs=[
        gr.Image(type="numpy", label="Upload Temperature Map"),
        gr.Dropdown(
            choices=[
                "extreme cold", "very cold", "moderate cold",
                "near normal", "slight warm", "moderate warm",
                "strong warm", "very strong warm", "extreme warm"
            ],
            label="Select Region Type"
        )
    ],
    outputs=gr.Image(type="numpy", label="Highlighted Region"),
    title="Temperature Mapping Demo",
    description="Upload a temperature anomaly map and select a region type to highlight."
)

interface.launch(debug=True)

