# -*- coding: utf-8 -*-
"""Training_phase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCfh8uLrFrcnpQ3xTkpu-m_lRxgP9FPS
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# Read image
img = cv2.imread("/content/Screenshot 2026-01-16 003649.png")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Reshape for KMeans
pixels = img.reshape(-1, 3).astype(np.float32)

# Number of color clusters
K = 9

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 50, 0.2)
_, labels, centers = cv2.kmeans(
    pixels, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS
)

labels = labels.reshape(img.shape[:2])
centers = centers.astype(int)

# Convert cluster centers to HSV to sort by temperature meaning
centers_hsv = cv2.cvtColor(
    centers.reshape(-1,1,3).astype(np.uint8),
    cv2.COLOR_RGB2HSV
).reshape(-1,3)

# Sort clusters by Hue (cold → warm)
sorted_idx = np.argsort(centers_hsv[:,0])[::-1]

# Relabel clusters in sorted order
new_labels = np.zeros_like(labels)
new_centers = []

for new_i, old_i in enumerate(sorted_idx):
    new_labels[labels == old_i] = new_i
    new_centers.append(centers[old_i])

new_centers = np.array(new_centers)

# Titles for each color cluster
label_titles = {
    0: "Extreme Cold Anomaly",
    1: "Very Cold Anomaly",
    2: "Moderate Cold Anomaly",
    3: "Near-Normal Temperature",
    4: "Slight Warm Anomaly",
    5: "Moderate Warm Anomaly",
    6: "Strong Warm Anomaly",
    7: "Extreme Warm Anomaly",
    8: "No Data / Masked Region"
}

# Create colored segmented image
segmented = np.zeros_like(img)
for i in range(K):
    segmented[new_labels == i] = new_centers[i]

# Plot
plt.figure(figsize=(12,6))
plt.imshow(segmented)
plt.title("K-Means Based Temperature Anomaly Classification")
plt.axis("off")

# Legend
legend_elements = [
    Patch(facecolor=new_centers[i]/255.0, label=label_titles[i])
    for i in range(K)
]

plt.legend(
    handles=legend_elements,
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.tight_layout()
plt.show()

# ==============================
# REGION QUERY BY LABEL (ADDITION)
# ==============================

# Class index → human-readable region
region_names = {
    0: "extreme cold",
    1: "very cold",
    2: "moderate cold",
    3: "near normal",
    4: "slight warm",
    5: "moderate warm",
    6: "strong warm",
    7: "very strong warm",
    8: "extreme warm"
}

# Reverse mapping (name → index)
name_to_class = {v: k for k, v in region_names.items()}

# -------- USER INPUT --------
user_input = input(
    "Enter region type (e.g., very cold, moderate warm, extreme warm): "
).lower().strip()

if user_input not in name_to_class:
    print("Invalid region name!")
else:
    class_id = name_to_class[user_input]

    # Create mask for selected region
    mask = (new_labels == class_id)

    # Highlight selected region
    highlighted = img.copy()
    highlighted[~mask] = [180, 180, 180]  # gray out other areas

    # Display result
    plt.figure(figsize=(10,5))
    plt.imshow(highlighted)
    plt.title(f"Highlighted Region: {region_names[class_id].title()}")
    plt.axis("off")
    plt.show()

